Make install.sh and uninstall.sh idempotent
yorickvanzweeden/Ubuntu-NordVPN-Indicator pull request #16
Opened 2019-11-03 19:08 UTC by yorickvanzweeden

Fixes #12 

What I did:
- Make `install.sh` idempotent. This makes script idempotent, and thus more easily automate-able using software like Chef, Puppet, or Ansible
-  Encapsulate echo contents with quotes. This improves code readability in editors like nano
- Install.sh only installs dependencies when they are not present
- Uninstall.sh offers to remove dependencies

2019-11-03 19:09 UTC, yorickvanzweeden commented
@ilcardella Could you have a look at my PR? Seems fair that I get reviewed too ;)

2019-11-03 20:01 UTC, ilcardella requested changes
Last comment. I would remove all the `sudo` keyword before each command. The caller would invoke the script as root in the best way he/she think.

We could even check at the very beginning of both scripts if the current user is root, and if not, exit with an error code and a message about requiring root permission

2019-11-03 20:01 UTC, ilcardella commented on install.sh
> +    echo "Indicator already running"
I would kill the process and then still start the new version that has just been installed. What do you think?

2019-11-03 20:01 UTC, ilcardella commented on uninstall.sh
> +read -p "Do you want to uninstall AppIndicator? " -n 1 -r
What about adding `[Y/n]` at the end of the message to make it clear what is the expected input?

2019-11-03 20:01 UTC, ilcardella commented on uninstall.sh
> +read -p "Do you want to uninstall AppIndicator? " -n 1 -r
Same for the messages below

2019-11-03 21:15 UTC, yorickvanzweeden commented
@ilcardella I wouldn't call sudo on entire scripts, as it could mess with permissions. For example: if you do a `cp`, it would run as root, and the resulting file would have root permissions. The resulting file can't be moved by normal users anymore.

We do require sudo for apt commands

2019-11-03 23:29 UTC, yorickvanzweeden commented on install.sh
> +    echo "Indicator already running"
Yes, seems good. See newest commit

2019-11-03 23:29 UTC, yorickvanzweeden commented on uninstall.sh
> +read -p "Do you want to uninstall AppIndicator? " -n 1 -r
Yes, seems good. See newest commit

2019-11-05 17:51 UTC, ilcardella approved these changes

2019-11-06 09:01 UTC, merged